// Uplift Summer 2026 completion certificates — generated by the certificate
// pipeline from public/uplift-certificate.html + uplift-2026-completers.csv.
// Keyed by mentee slug; file paths live under public/certificates/.

export const CERTIFICATES = {
  "natalie-kitts": {
    "file": "/certificates/Uplift Certificate of Completion - Natalie Kitts.pdf",
    "id": "UP26-001",
    "date": "August 4, 2026"
  },
  "pearl-gabel": {
    "file": "/certificates/Uplift Certificate of Completion - Pearl Gabel.pdf",
    "id": "UP26-002",
    "date": "August 4, 2026"
  },
  "daniel-patton": {
    "file": "/certificates/Uplift Certificate of Completion - Daniel Patton.pdf",
    "id": "UP26-003",
    "date": "August 4, 2026"
  },
  "rajesh-ivaturi": {
    "file": "/certificates/Uplift Certificate of Completion - Rajesh Ivaturi.pdf",
    "id": "UP26-004",
    "date": "August 4, 2026"
  },
  "chandni-patel": {
    "file": "/certificates/Uplift Certificate of Completion - Chandni Patel.pdf",
    "id": "UP26-005",
    "date": "August 4, 2026"
  },
  "evan-peneiras": {
    "file": "/certificates/Uplift Certificate of Completion - Evan Peneiras.pdf",
    "id": "UP26-006",
    "date": "August 4, 2026"
  },
  "radha-ratnala": {
    "file": "/certificates/Uplift Certificate of Completion - Radha Ratnala.pdf",
    "id": "UP26-007",
    "date": "August 4, 2026"
  },
  "jhamar-youngblood": {
    "file": "/certificates/Uplift Certificate of Completion - Jhamar Youngblood.pdf",
    "id": "UP26-008",
    "date": "August 4, 2026"
  },
  "sonali-chilupuri": {
    "file": "/certificates/Uplift Certificate of Completion - Sonali Chilupuri.pdf",
    "id": "UP26-009",
    "date": "August 4, 2026"
  },
  "sarah-inoue": {
    "file": "/certificates/Uplift Certificate of Completion - Sarah Inoue.pdf",
    "id": "UP26-010",
    "date": "August 4, 2026"
  },
  "adeola-adeoye-davids": {
    "file": "/certificates/Uplift Certificate of Completion - Adeola Adeoye-Davids.pdf",
    "id": "UP26-011",
    "date": "August 4, 2026"
  },
  "lina-escobar": {
    "file": "/certificates/Uplift Certificate of Completion - Lina Escobar.pdf",
    "id": "UP26-012",
    "date": "August 4, 2026"
  },
  "kima-danjou": {
    "file": "/certificates/Uplift Certificate of Completion - Kima D'Anjou.pdf",
    "id": "UP26-013",
    "date": "August 4, 2026"
  },
  "shanthi-viswanathan": {
    "file": "/certificates/Uplift Certificate of Completion - Shanthi Viswanathan.pdf",
    "id": "UP26-014",
    "date": "August 4, 2026"
  },
  "angela-aricatt": {
    "file": "/certificates/Uplift Certificate of Completion - Angela Aricatt.pdf",
    "id": "UP26-015",
    "date": "August 4, 2026"
  },
  "anthony-caruso": {
    "file": "/certificates/Uplift Certificate of Completion - Anthony Caruso.pdf",
    "id": "UP26-016",
    "date": "August 4, 2026"
  },
  "annalyce-dagostino-gavin": {
    "file": "/certificates/Uplift Certificate of Completion - Annalyce D'Agostino-Gavin.pdf",
    "id": "UP26-017",
    "date": "August 4, 2026"
  },
  "rachel-hayes": {
    "file": "/certificates/Uplift Certificate of Completion - Rachel Hayes.pdf",
    "id": "UP26-018",
    "date": "August 4, 2026"
  },
  "ekaterina-kashkina": {
    "file": "/certificates/Uplift Certificate of Completion - Ekaterina Kashkina.pdf",
    "id": "UP26-019",
    "date": "August 4, 2026"
  },
  "elaf-mahmoud": {
    "file": "/certificates/Uplift Certificate of Completion - Elaf Mahmoud.pdf",
    "id": "UP26-020",
    "date": "August 4, 2026"
  },
  "tosca-marleen": {
    "file": "/certificates/Uplift Certificate of Completion - Tosca Marleen.pdf",
    "id": "UP26-021",
    "date": "August 4, 2026"
  },
  "nina-mladenovski": {
    "file": "/certificates/Uplift Certificate of Completion - Nina Mladenovski.pdf",
    "id": "UP26-022",
    "date": "August 4, 2026"
  },
  "jordan-river-samuel": {
    "file": "/certificates/Uplift Certificate of Completion - Jordan-River Samuel.pdf",
    "id": "UP26-023",
    "date": "August 4, 2026"
  },
  "chirag-shah": {
    "file": "/certificates/Uplift Certificate of Completion - Chirag Shah.pdf",
    "id": "UP26-024",
    "date": "August 4, 2026"
  },
  "alisha-sharma": {
    "file": "/certificates/Uplift Certificate of Completion - Alisha Sharma.pdf",
    "id": "UP26-025",
    "date": "August 4, 2026"
  },
  "shell-bobev": {
    "file": "/certificates/Uplift Certificate of Completion - Shell Bobev.pdf",
    "id": "UP26-026",
    "date": "August 4, 2026"
  },
  "priyal-levine": {
    "file": "/certificates/Uplift Certificate of Completion - Priyal Levine.pdf",
    "id": "UP26-027",
    "date": "August 4, 2026"
  },
  "eliana-zebro": {
    "file": "/certificates/Uplift Certificate of Completion - Eliana Zebro.pdf",
    "id": "UP26-028",
    "date": "August 4, 2026"
  },
  "elisa-charters": {
    "file": "/certificates/Uplift Certificate of Completion - Elisa Charters.pdf",
    "id": "UP26-029",
    "date": "August 4, 2026"
  },
  "kevin-navarro": {
    "file": "/certificates/Uplift Certificate of Completion - Kevin Navarro.pdf",
    "id": "UP26-030",
    "date": "August 4, 2026"
  },
  "abhaya-pawar": {
    "file": "/certificates/Uplift Certificate of Completion - Abhaya Pawar.pdf",
    "id": "UP26-031",
    "date": "August 4, 2026"
  },
  "stephanie-scott-bradshaw": {
    "file": "/certificates/Uplift Certificate of Completion - Stephanie Scott-Bradshaw.pdf",
    "id": "UP26-032",
    "date": "August 4, 2026"
  },
  "bejan-moers": {
    "file": "/certificates/Uplift Certificate of Completion - Bejan Moers.pdf",
    "id": "UP26-033",
    "date": "August 4, 2026"
  },
  "jeremy-ruiz-villavicencio": {
    "file": "/certificates/Uplift Certificate of Completion - Jeremy Ruiz Villavicencio.pdf",
    "id": "UP26-034",
    "date": "August 4, 2026"
  },
  "harshil-thakkar": {
    "file": "/certificates/Uplift Certificate of Completion - Harshil Thakkar.pdf",
    "id": "UP26-035",
    "date": "August 4, 2026"
  },
  "logan-jones": {
    "file": "/certificates/Uplift Certificate of Completion - Logan Jones.pdf",
    "id": "UP26-036",
    "date": "August 4, 2026"
  },
  "sharon-joseph": {
    "file": "/certificates/Uplift Certificate of Completion - Sharon Joseph.pdf",
    "id": "UP26-037",
    "date": "August 4, 2026"
  },
  "lianna-lariccia": {
    "file": "/certificates/Uplift Certificate of Completion - Lianna LaRiccia.pdf",
    "id": "UP26-038",
    "date": "August 4, 2026"
  },
  "paula-machado-jackler": {
    "file": "/certificates/Uplift Certificate of Completion - Paula Machado Jackler.pdf",
    "id": "UP26-039",
    "date": "August 4, 2026"
  },
  "hamza-zafar": {
    "file": "/certificates/Uplift Certificate of Completion - Hamza Zafar.pdf",
    "id": "UP26-040",
    "date": "August 4, 2026"
  },
  "gunjan-aggarwal": {
    "file": "/certificates/Uplift Certificate of Completion - Gunjan Aggarwal.pdf",
    "id": "UP26-041",
    "date": "August 2026"
  },
  "debbie-douglas-henry": {
    "file": "/certificates/Uplift Certificate of Completion - Debbie Douglas-Henry.pdf",
    "id": "UP26-042",
    "date": "August 2026"
  },
  "gifty-anane": {
    "file": "/certificates/Uplift Certificate of Completion - Gifty Anane.pdf",
    "id": "UP26-043",
    "date": "August 2026"
  },
  "jean-guerdy-paul": {
    "file": "/certificates/Uplift Certificate of Completion - Jean Guerdy Paul.pdf",
    "id": "UP26-044",
    "date": "August 2026"
  },
  "pierre-girgis": {
    "file": "/certificates/Uplift Certificate of Completion - Pierre Girgis.pdf",
    "id": "UP26-045",
    "date": "August 2026"
  },
  "aliya-laliwala": {
    "file": "/certificates/Uplift Certificate of Completion - Aliya Laliwala.pdf",
    "id": "UP26-046",
    "date": "August 2026"
  }
};
