// GENERATED FILE — do not edit by hand.
//   node scripts/build-fall-cohort.mjs
//
// Just the slugs from lib/fall-cohort.js, as a flat literal. Separate on
// purpose: lib/fall-roster.js imports this and is bundled for the browser,
// so it must not reach the founder records themselves.

export const FALL_FOUNDER_SLUGS = [
  "takeerah-jones",
  "laura-acosta",
  "ceana-santori",
  "clevon-brown",
  "carolina-galvis",
  "collin-coke",
  "christina-brown",
  "mayank-doultani",
  "vishruti-mehta",
  "neha-panwar",
  "kristen-chin",
  "ifeanyi-osuji",
  "jairo-contreras",
  "jt-keitt",
  "durvish-paliwal",
  "udbhav-gupta",
  "sameer-dhawan",
  "ninad-dhoble",
  "sumayya-tabassum-shaik",
  "johnny-pillacela",
  "lola-abanum",
  "tami-brown",
  "kimberly-butler",
  "brittany-payton",
  "tamara-fleming",
  "melinda-rushing",
  "rachel-khasky-levy",
  "rosalind-griffie",
  "tammy-hollaway",
  "megan-fonseca",
  "suresh-y",
  "jannie-wolff",
  "david-singletary",
  "mehul-shah",
  "naomie-sophia-renarde",
  "sanjeev-wadhwa",
  "maureen-teyssier",
  "livingston-steele",
  "karleen-leveille",
  "emery-smiolia",
  "john-chang",
  "talaya-loftin",
  "amy-bohne",
  "raj-somas",
  "davina-ward",
  "nana-abban",
  "renee-williams",
  "deb-di-gregorio",
  "paula-muller",
  "patricia-lucas-schnarre",
];
