// All 74 Uplift Summer 2026 mentees + 1 test entry
// slug is used for the URL: uplift.techunited.co/[slug]

export const MENTEES = [
  // ── COHORT 1 — Edison ────────────────────────────────────────────────────
  {
    slug: "gifty-anane",
    cohort: 1,
    first: "Gifty", last: "Anane",
    company: "Wash Lodge",
    stage: "MVP / Early build",
    industry: "Retail / Marketplace / E-commerce",
    county: "Middlesex",
    primaryFocus: "Sense-checking decisions with an experienced operator",
    secondaryFoci: ["Go-to-market & customer acquisition"],
    mentor: { name: "Tom Oser", company: "Pipeline Strategy Partners", title: "CEO, Managing Partner", initials: "TO", tags: ["Strategic sounding board", "Go-to-market", "Retail / E-commerce"] },
  },
  {
    slug: "anthony-caruso",
    cohort: 1,
    linkedin: "https://www.linkedin.com/in/anthonycaruso10/",
    first: "Anthony", last: "Caruso",
    company: "Contextral",
    stage: "Early traction",
    industry: "AI / Data / ML",
    county: "Ocean",
    primaryFocus: "Go-to-market & customer acquisition",
    secondaryFoci: ["Fundraising strategy & investor readiness"],
    mentor: { name: "Ed Sawma", company: "Ed Sawma Consulting", title: "Principal Consultant", initials: "ES", tags: ["Go-to-market", "AI / Data / ML", "Early traction"] },
  },
  {
    slug: "sonali-chilupuri",
    cohort: 1,
    linkedin: "https://www.linkedin.com/in/sonalichilupuri/",
    first: "Sonali", last: "Chilupuri",
    company: "Recky Solutions LLC",
    stage: "Early traction",
    industry: "Enterprise SaaS / B2B",
    county: "Middlesex",
    primaryFocus: "Go-to-market & customer acquisition",
    secondaryFoci: ["Fundraising strategy & investor readiness", "Clarifying near-term company priorities"],
    mentor: { name: "Eric Schmalzbauer", company: "Prospective", title: "CEO, co-founder", initials: "ES", tags: ["Go-to-market", "Enterprise SaaS / B2B", "Early traction"] },
  },
  {
    slug: "neha-chopade",
    cohort: 1,
    linkedin: "https://www.linkedin.com/in/nehachopade/",
    first: "Neha", last: "Chopade",
    company: "Meta",
    stage: "Idea stage",
    industry: "Other",
    county: "Hudson",
    primaryFocus: "Clarifying near-term company priorities",
    secondaryFoci: ["Understanding the NJ/regional startup ecosystem", "Sense-checking decisions with an experienced operator"],
    mentor: { name: "Goncalo Esteves", company: "Self Defense 4 All LLC", title: "Founder and CEO", initials: "GE", tags: ["Founder decision-making", "Strategic sounding board"] },
  },
  {
    slug: "lina-escobar",
    cohort: 1,
    linkedin: "https://www.linkedin.com/in/lina-escobar-13809a8b",
    first: "Lina", last: "Escobar",
    company: "Sweet Aurora Soap & Candle",
    stage: "Revenue-generating",
    industry: "CPG / Consumer Brands",
    primaryFocus: "Go-to-market & customer acquisition",
    secondaryFoci: ["Product strategy & roadmap decisions", "Hiring, team structure & leadership"],
    mentor: { name: "Rikin Diwan", company: "lowercaseb2b.com / popform.ai", title: "CEO", initials: "RD", tags: ["Go-to-market", "CPG / Consumer Brands", "Revenue-generating"] },
  },
  {
    slug: "victoria-hosendorf",
    cohort: 1,
    linkedin: "https://www.linkedin.com/in/victoria-hosendorf-a83601313/",
    first: "Victoria", last: "Hosendorf",
    company: "Hosendorf & Associates, LLC",
    stage: "Idea stage",
    industry: "Other",
    primaryFocus: "Refining pitch or company narrative",
    secondaryFoci: ["Clarifying near-term company priorities"],
    mentor: { name: "Felicia Palmer", company: "tapyoca Inc", title: "CEO", initials: "FP", tags: ["Pitch & narrative", "Idea stage"] },
  },
  {
    slug: "sarah-inoue",
    cohort: 1,
    first: "Sarah", last: "Inoue",
    company: "Crafty Dessert LLC",
    stage: "Early traction",
    industry: "Retail / Marketplace / E-commerce",
    county: "Bergen",
    primaryFocus: "Preparing for a major inflection point (raise, launch, pivot, expansion)",
    secondaryFoci: ["Go-to-market & customer acquisition"],
    mentor: { name: "Sid Nag", company: "Tekonyx", title: "President and CEO", initials: "SN", tags: ["Inflection-point navigation", "Retail / E-commerce"] },
  },
  {
    slug: "favio-jasso",
    cohort: 1,
    linkedin: "https://www.linkedin.com/in/faviojasso/",
    first: "Favio", last: "Jasso",
    company: "AnatomyQuest",
    stage: "MVP / Early build",
    industry: "Enterprise SaaS / B2B",
    primaryFocus: "Sense-checking decisions with an experienced operator",
    secondaryFoci: ["Product strategy & roadmap decisions"],
    mentor: { name: "Ari Rabban", company: "Phone.com, Inc.", title: "CEO & Co-founder", initials: "AR", tags: ["Strategic sounding board", "Enterprise SaaS / B2B", "MVP stage"] },
  },
  {
    slug: "jagannadh-kanumuri",
    cohort: 1,
    linkedin: "https://www.linkedin.com/in/jagannadhkanumuri",
    first: "Jagannadh", last: "Kanumuri",
    company: "ACI Infotech",
    stage: "Growth-stage",
    industry: "AI / Data / ML",
    county: "Somerset",
    primaryFocus: "Go-to-market & customer acquisition",
    secondaryFoci: ["Operational scaling and systems"],
    mentor: { name: "Rahul Mehendale", company: "Live150.ai", title: "CEO", initials: "RM", tags: ["Go-to-market", "AI / Data / ML", "Growth-stage"] },
  },
  {
    slug: "soheil-khosravinejad",
    cohort: 1,
    linkedin: "https://www.linkedin.com/in/soheilkh/",
    first: "Soheil", last: "Khosravinejad",
    company: "DRIFTLANE",
    stage: "Early traction",
    industry: "Media / Marketing / Advertising",
    primaryFocus: "Preparing for a major inflection point (raise, launch, pivot, expansion)",
    secondaryFoci: ["Fundraising strategy & investor readiness"],
    mentor: { name: "Vishal Soni", company: "Virid Biosciences", title: "CEO", initials: "VS", tags: ["Inflection-point navigation", "Media / Marketing", "Early traction"] },
  },
  {
    slug: "alina-okun",
    cohort: 1,
    linkedin: "https://www.linkedin.com/in/alinaokun/",
    first: "Alina", last: "Okun",
    company: "Nariway",
    stage: "MVP / Early build",
    industry: "Other",
    county: "Bergen",
    primaryFocus: "Go-to-market & customer acquisition",
    secondaryFoci: ["Refining pitch or company narrative", "Product strategy & roadmap decisions"],
    mentor: { name: "Tom Oser", company: "Pipeline Strategy Partners", title: "CEO, Managing Partner", initials: "TO", tags: ["Go-to-market", "Pitch & narrative", "MVP stage"] },
  },
  {
    slug: "jerry-primus",
    cohort: 1,
    first: "Jerry", last: "Primus",
    company: "PCLinkup",
    stage: "Revenue-generating",
    industry: "AI / Data / ML",
    county: "Somerset",
    primaryFocus: "Go-to-market & customer acquisition",
    secondaryFoci: ["Fundraising strategy & investor readiness"],
    mentor: { name: "Joe Spivack", company: "Jumpstart NJ Angel Network", title: "Board Member", initials: "JS", tags: ["Go-to-market", "AI / Data / ML", "Fundraising strategy"] },
  },
  {
    slug: "andrea-vernengo",
    cohort: 1,
    first: "Andrea", last: "Vernengo",
    company: "TrueSkin",
    stage: "MVP / Early build",
    industry: "Hardware / Manufacturing",
    county: "Camden",
    primaryFocus: "Fundraising strategy & investor readiness",
    secondaryFoci: ["Product strategy & roadmap decisions", "Go-to-market & customer acquisition"],
    mentor: { name: "ebun okubanjo", company: "mssuzie.io", title: "CEO/Co-Founder", initials: "EO", tags: ["Fundraising strategy", "Hardware / Manufacturing", "MVP stage"] },
  },
  {
    slug: "jedidiah-worrell",
    cohort: 1,
    first: "Jedidiah", last: "Worrell",
    company: "Unnamed (Idea Stage)",
    stage: "Idea stage",
    industry: "Retail / Marketplace / E-commerce",
    county: "Mercer",
    primaryFocus: "Product strategy & roadmap decisions",
    secondaryFoci: ["Clarifying near-term company priorities", "Fundraising strategy & investor readiness"],
    mentor: { name: "Natalie Kaminski", company: "JetRockets", title: "Co-Founder & CEO", initials: "NK", tags: ["Product & roadmap", "Retail / E-commerce", "Idea stage"] },
  },
  {
    slug: "jhamar-youngblood",
    cohort: 1,
    first: "Jhamar", last: "Youngblood",
    company: "Brickcity",
    stage: "Early traction",
    industry: "Other",
    county: "Essex",
    primaryFocus: "Go-to-market & customer acquisition",
    secondaryFoci: [],
    mentor: { name: "Marty Coleman", company: "Entrepreneur/Investor/Mentor", title: "Entrepreneur/Investor/Mentor", initials: "MC", tags: ["Go-to-market", "Early traction"] },
  },
  {
    slug: "hamza-zafar",
    cohort: 1,
    linkedin: "https://www.linkedin.com/in/hamza-zafar-7a14b5340/",
    first: "Hamza", last: "Zafar",
    company: "HHALI LLC",
    stage: "MVP / Early build",
    industry: "AI / Data / ML",
    county: "Middlesex",
    primaryFocus: "Go-to-market & customer acquisition",
    secondaryFoci: ["Fundraising strategy & investor readiness"],
    mentor: { name: "Rahul Mehendale", company: "Live150.ai", title: "CEO", initials: "RM", tags: ["Go-to-market", "AI / Data / ML", "MVP stage"] },
  },

  // ── COHORT 2 — Hopper ────────────────────────────────────────────────────
  {
    slug: "annalyce-dagostino-gavin",
    cohort: 2,
    first: "Annalyce", last: "D'Agostino-Gavin",
    company: "Focus Posters®",
    stage: "Early traction",
    industry: "Other",
    primaryFocus: "Preparing for a major inflection point (raise, launch, pivot, expansion)",
    secondaryFoci: ["Refining pitch or company narrative"],
    mentor: { name: "Joseph Gadino", company: "Retired from NTT Data Business Solutions", title: "VP Advisory Services", initials: "JG", tags: ["Inflection-point navigation", "Pitch & narrative"] },
  },
  {
    slug: "debbie-douglas-henry",
    cohort: 2,
    first: "Debbie", last: "Douglas-Henry",
    company: "3DHR Consulting, LLC",
    stage: "Early traction",
    industry: "Media / Marketing / Advertising",
    county: "Essex",
    primaryFocus: "Go-to-market & customer acquisition",
    secondaryFoci: ["Sense-checking decisions with an experienced operator"],
    mentor: { name: "Wadnes Castelly", company: "KAPAB Marketing Consultancy LLC", title: "Founder", initials: "WC", tags: ["Go-to-market", "Media / Marketing", "Early traction"] },
  },
  {
    slug: "pearl-gabel",
    cohort: 2,
    first: "Pearl", last: "Gabel",
    company: "TBD",
    stage: "Idea stage",
    industry: "Media / Marketing / Advertising",
    primaryFocus: "Clarifying near-term company priorities",
    secondaryFoci: ["Product strategy & roadmap decisions", "Understanding the NJ/regional startup ecosystem"],
    mentor: { name: "Jeffrey Allen", company: "The Mariner Group, LLC", title: "CEO", initials: "JA", tags: ["Founder decision-making", "Media / Marketing", "Idea stage"] },
  },
  {
    slug: "ekaterina-kashkina",
    cohort: 2,
    first: "Ekaterina", last: "Kashkina",
    company: "Stealth-mode molecular diagnostics startup",
    stage: "MVP / Early build",
    industry: "Other",
    county: "Camden",
    primaryFocus: "Fundraising strategy & investor readiness",
    secondaryFoci: ["Refining pitch or company narrative"],
    mentor: { name: "Marty Coleman", company: "Entrepreneur/Investor/Mentor", title: "Entrepreneur/Investor/Mentor", initials: "MC", tags: ["Fundraising strategy", "MVP stage"] },
  },
  {
    slug: "naveen-kumar",
    cohort: 2,
    first: "Naveen", last: "Kumar",
    company: "Truxt",
    stage: "Early traction",
    industry: "Enterprise SaaS / B2B",
    county: "Bergen",
    primaryFocus: "Go-to-market & customer acquisition",
    secondaryFoci: ["Fundraising strategy & investor readiness", "Operational scaling and systems"],
    mentor: { name: "Mark Nelson", company: "Pivot Fuel", title: "CEO", initials: "MN", tags: ["Go-to-market", "Enterprise SaaS / B2B", "Fundraising strategy"] },
  },
  {
    slug: "elaf-mahmoud",
    cohort: 2,
    first: "Elaf", last: "Mahmoud",
    company: "Elune Health",
    stage: "Idea stage",
    industry: "CPG / Consumer Brands",
    county: "Morris",
    primaryFocus: "Refining pitch or company narrative",
    secondaryFoci: ["Go-to-market & customer acquisition"],
    mentor: { name: "Jessie Lee", company: "SmartTravel.com", title: "GTM, Health Insurance", initials: "JL", tags: ["Pitch & narrative", "Go-to-market", "CPG / Consumer Brands"] },
  },
  {
    slug: "tosca-marleen",
    cohort: 2,
    first: "Tosca", last: "Marleen",
    company: "Tend to Belle",
    stage: "MVP / Early build",
    industry: "Retail / Marketplace / E-commerce",
    primaryFocus: "Hiring, team structure & leadership",
    secondaryFoci: [],
    mentor: { name: "Natalie Kaminski", company: "JetRockets", title: "Co-Founder & CEO", initials: "NK", tags: ["Hiring & leadership", "Retail / E-commerce", "MVP stage"] },
  },
  {
    slug: "ahmed-metwoali",
    cohort: 2,
    first: "Ahmed", last: "Metwoali",
    company: "Sphinque",
    stage: "MVP / Early build",
    industry: "Enterprise SaaS / B2B",
    primaryFocus: "Go-to-market & customer acquisition",
    secondaryFoci: ["Refining pitch or company narrative", "Product strategy & roadmap decisions"],
    mentor: { name: "Vikram Wadhawan", company: "Vasitum Inc", title: "Founder & CEO", initials: "VW", tags: ["Go-to-market", "Enterprise SaaS / B2B", "Pitch & narrative"] },
  },
  {
    slug: "nina-mladenovski",
    cohort: 2,
    first: "Nina", last: "Mladenovski",
    company: "Zenia Graph",
    stage: "Revenue-generating",
    industry: "AI / Data / ML",
    primaryFocus: "Go-to-market & customer acquisition",
    secondaryFoci: ["Operational scaling and systems", "Sense-checking decisions with an experienced operator"],
    mentor: { name: "Clare DeNicola", company: "the10company", title: "Principal", initials: "CD", tags: ["Go-to-market", "AI / Data / ML", "Revenue-generating"] },
  },
  {
    slug: "bejan-moers",
    cohort: 2,
    first: "Bejan", last: "Moers",
    company: "United Solution",
    stage: "Early traction",
    industry: "Other",
    county: "Hudson",
    primaryFocus: "Preparing for a major inflection point (raise, launch, pivot, expansion)",
    secondaryFoci: ["Fundraising strategy & investor readiness", "Go-to-market & customer acquisition"],
    mentor: { name: "Dan Gura", company: "Hugo Neu", title: "Director BD/Consultant", initials: "DG", tags: ["Inflection-point navigation", "Fundraising strategy", "Go-to-market"] },
  },
  {
    slug: "emilia-savich",
    cohort: 2,
    first: "Emilia", last: "Savich",
    company: "AnatomyQuest",
    stage: "MVP / Early build",
    industry: "Enterprise SaaS / B2B",
    county: "Ocean",
    primaryFocus: "Sense-checking decisions with an experienced operator",
    secondaryFoci: ["Product strategy & roadmap decisions"],
    mentor: { name: "Ari Rabban", company: "Phone.com, Inc.", title: "CEO & Co-founder", initials: "AR", tags: ["Strategic sounding board", "Enterprise SaaS / B2B", "MVP stage"] },
  },
  {
    slug: "alisha-sharma",
    cohort: 2,
    first: "Alisha", last: "Sharma",
    company: "Undecided",
    stage: "Idea stage",
    industry: "Other",
    county: "Morris",
    primaryFocus: "Product strategy & roadmap decisions",
    secondaryFoci: ["Fundraising strategy & investor readiness", "Preparing for a major inflection point"],
    mentor: { name: "Rikin Diwan", company: "lowercaseb2b.com / popform.ai", title: "CEO", initials: "RD", tags: ["Product & roadmap", "Fundraising strategy"] },
  },
  {
    slug: "angie-tirado",
    cohort: 2,
    first: "Angie", last: "Tirado",
    company: "Fluenci",
    stage: "MVP / Early build",
    industry: "Retail / Marketplace / E-commerce",
    primaryFocus: "Product strategy & roadmap decisions",
    secondaryFoci: [],
    mentor: { name: "Malak Atut", company: "Yalla Now AI", title: "Co-Founder", initials: "MA", tags: ["Product & roadmap", "Retail / E-commerce", "MVP stage"] },
  },
  {
    slug: "justin-savage",
    cohort: 2,
    first: "Justin", last: "Savage",
    company: "STEAM FOR ME",
    stage: "Early traction",
    industry: "Enterprise SaaS / B2B",
    county: "Essex",
    primaryFocus: "Fundraising strategy & investor readiness",
    secondaryFoci: [],
    mentor: { name: "Aizaz Shariff", company: "Stratsphere", title: "Principal", initials: "AS", tags: ["Fundraising strategy", "Enterprise SaaS / B2B"] },
  },
  {
    slug: "shounak-thaker",
    cohort: 2,
    first: "Shounak", last: "Thaker",
    company: "Arnex Solutions LLC",
    stage: "Revenue-generating",
    industry: "Other",
    county: "Mercer",
    primaryFocus: "Fundraising strategy & investor readiness",
    secondaryFoci: ["Go-to-market & customer acquisition"],
    mentor: { name: "Bruno Bilik", company: "91.life", title: "Chief Revenue Officer", initials: "BB", tags: ["Fundraising strategy", "Go-to-market", "Revenue-generating"] },
  },

  // ── COHORT 3 — Bardeen ───────────────────────────────────────────────────
  {
    slug: "adeola-adeoye-davids",
    cohort: 3,
    first: "Adeola", last: "Adeoye-Davids",
    company: "Local Window",
    stage: "MVP / Early build",
    industry: "Media / Marketing / Advertising",
    county: "Passaic",
    primaryFocus: "Operational scaling and systems",
    secondaryFoci: [],
    mentor: { name: "Basia Walska", company: "Natera Inc.", title: "Manager, Clinical Trial Contracts", initials: "BW", tags: ["Operational scaling", "MVP stage"] },
  },
  {
    slug: "shell-bobev",
    cohort: 3,
    first: "Shell", last: "Bobev",
    company: "Disrupt The Gap",
    stage: "Revenue-generating",
    industry: "Government / Civic / Policy",
    county: "Morris",
    primaryFocus: "Product strategy & roadmap decisions",
    secondaryFoci: ["Sense-checking decisions with an experienced operator"],
    mentor: { name: "Roman Tsibulevskiy", company: "Dentons US LLP", title: "Counsel, patent attorney", initials: "RT", tags: ["Product & roadmap", "Government / Civic / Policy", "Revenue-generating"] },
  },
  {
    slug: "stephanie-cwynar",
    cohort: 3,
    first: "Stephanie", last: "Cwynar",
    company: "Pinterest",
    stage: "Idea stage",
    industry: "Other",
    primaryFocus: "Sense-checking decisions with an experienced operator",
    secondaryFoci: ["Fundraising strategy & investor readiness", "Understanding the NJ/regional startup ecosystem"],
    mentor: { name: "Dee Marshall", company: "AI Training Plus", title: "Chief Executive Officer", initials: "DM", tags: ["Strategic sounding board", "Idea stage"] },
  },
  {
    slug: "pierre-girgis",
    cohort: 3,
    first: "Pierre", last: "Girgis",
    company: "Veriflo LLC",
    stage: "Idea stage",
    industry: "AI / Data / ML",
    county: "Bergen",
    primaryFocus: "Product strategy & roadmap decisions",
    secondaryFoci: ["Fundraising strategy & investor readiness"],
    mentor: { name: "Aizaz Shariff", company: "Stratsphere", title: "Principal", initials: "AS", tags: ["Product & roadmap", "AI / Data / ML", "Idea stage"] },
  },
  {
    slug: "pradeep-kumar-gohil",
    cohort: 3,
    first: "Pradeep Kumar", last: "Gohil",
    company: "World Micro Stock Vinimay USA LLC",
    stage: "Idea stage",
    industry: "Other",
    primaryFocus: "Fundraising strategy & investor readiness",
    secondaryFoci: ["Refining pitch or company narrative", "Go-to-market & customer acquisition"],
    mentor: { name: "Joseph Gadino", company: "Retired from NTT Data Business Solutions", title: "VP Advisory Services", initials: "JG", tags: ["Fundraising strategy", "Pitch & narrative"] },
  },
  {
    slug: "daniel-lee",
    cohort: 3,
    first: "Daniel", last: "Lee",
    company: "Bruce AI (OnwardJustice Inc.)",
    stage: "Revenue-generating",
    industry: "AI / Data / ML",
    primaryFocus: "Fundraising strategy & investor readiness",
    secondaryFoci: ["Go-to-market & customer acquisition", "Operational scaling and systems"],
    mentor: { name: "Joe Spivack", company: "Jumpstart NJ Angel Network", title: "Board Member", initials: "JS", tags: ["Fundraising strategy", "AI / Data / ML", "Revenue-generating"] },
  },
  {
    slug: "paula-machado-jackler",
    cohort: 3,
    first: "Paula", last: "Machado Jackler",
    company: "Ozzie",
    stage: "MVP / Early build",
    industry: "Finance / Fintech",
    primaryFocus: "Go-to-market & customer acquisition",
    secondaryFoci: ["Product strategy & roadmap decisions", "Founder decision-making & tradeoff"],
    mentor: { name: "Eric Schmalzbauer", company: "Prospective", title: "CEO, co-founder", initials: "ES", tags: ["Go-to-market", "Finance / Fintech", "MVP stage"] },
  },
  {
    slug: "idongesit-obeya",
    cohort: 3,
    first: "Idongesit", last: "Obeya",
    company: "Altruistic Scribe",
    stage: "Early traction",
    industry: "Enterprise SaaS / B2B",
    primaryFocus: "Go-to-market & customer acquisition",
    secondaryFoci: ["Operational scaling and systems"],
    mentor: { name: "Vikram Wadhawan", company: "Vasitum Inc", title: "Founder & CEO", initials: "VW", tags: ["Go-to-market", "Enterprise SaaS / B2B", "Early traction"] },
  },
  {
    slug: "jean-guerdy-paul",
    cohort: 3,
    first: "Jean Guerdy", last: "Paul",
    company: "TETHRRA",
    stage: "Early traction",
    industry: "Enterprise SaaS / B2B",
    county: "Monmouth",
    primaryFocus: "Refining pitch or company narrative",
    secondaryFoci: ["Go-to-market & customer acquisition"],
    mentor: { name: "Roman Tsibulevskiy", company: "Dentons US LLP", title: "Counsel, patent attorney", initials: "RT", tags: ["Pitch & narrative", "Enterprise SaaS / B2B", "Early traction"] },
  },
  {
    slug: "evan-peneiras",
    cohort: 3,
    first: "Evan", last: "Peneiras",
    company: "Nooriva",
    stage: "MVP / Early build",
    industry: "AI / Data / ML",
    county: "Essex",
    primaryFocus: "Understanding the NJ/regional startup ecosystem",
    secondaryFoci: [],
    mentor: { name: "Basia Walska", company: "Natera Inc.", title: "Manager, Clinical Trial Contracts", initials: "BW", tags: ["NJ ecosystem guidance", "AI / Data / ML"] },
  },
  {
    slug: "alok-rai",
    cohort: 3,
    first: "Alok", last: "Rai",
    company: "Dumroo.ai",
    stage: "Early traction",
    industry: "Other",
    county: "Essex",
    primaryFocus: "Fundraising strategy & investor readiness",
    secondaryFoci: ["Go-to-market & customer acquisition"],
    mentor: { name: "Connie Pascal", company: "Rutgers - School of Communication & Information", title: "Lecturer III", initials: "CP", tags: ["Fundraising strategy", "Early traction"] },
  },
  {
    slug: "radha-ratnala",
    cohort: 3,
    first: "Radha", last: "Ratnala",
    company: "Rekogni AI",
    stage: "MVP / Early build",
    industry: "Enterprise SaaS / B2B",
    county: "Middlesex",
    primaryFocus: "Go-to-market & customer acquisition",
    secondaryFoci: [],
    mentor: { name: "Pavan Kumar", company: "3pm Ventures LLC", title: "Partner", initials: "PK", tags: ["Go-to-market", "Enterprise SaaS / B2B", "MVP stage"] },
  },
  {
    slug: "abhi-ray",
    cohort: 3,
    first: "Abhi", last: "Ray",
    company: "Freelance Software Engineer",
    stage: "MVP / Early build",
    industry: "AI / Data / ML",
    county: "Middlesex",
    primaryFocus: "Product strategy & roadmap decisions",
    secondaryFoci: ["Operational scaling and systems"],
    mentor: { name: "Dennis Yuscavitch", company: "Accrete Inc.", title: "VP, Marketing", initials: "DY", tags: ["Product & roadmap", "AI / Data / ML", "MVP stage"] },
  },
  {
    slug: "stephanie-scott-bradshaw",
    cohort: 3,
    first: "Stephanie", last: "Scott-Bradshaw",
    company: "First and Last PR",
    stage: "Revenue-generating",
    industry: "Media / Marketing / Advertising",
    county: "Hudson",
    primaryFocus: "Sense-checking decisions with an experienced operator",
    secondaryFoci: ["Founder decision-making & tradeoff"],
    mentor: { name: "Orin Davis", company: "Quality of Life Laboratory", title: "Principal", initials: "OD", tags: ["Strategic sounding board", "Media / Marketing", "Revenue-generating"] },
  },
  {
    slug: "shanthi-viswanathan",
    cohort: 3,
    first: "Shanthi", last: "Viswanathan",
    company: "Infivista Inc",
    stage: "Early traction",
    industry: "Other",
    county: "Hudson",
    primaryFocus: "Go-to-market & customer acquisition",
    secondaryFoci: ["Clarifying near-term company priorities", "Product strategy & roadmap decisions"],
    mentor: { name: "Marc Saint-Ulysse", company: "Northgate Operations", title: "Founder", initials: "MS", tags: ["Go-to-market", "Early traction"] },
  },

  // ── COHORT 4 — Lawrence ──────────────────────────────────────────────────
  {
    slug: "ebunoluwa-adenekan",
    cohort: 4,
    first: "Ebunoluwa", last: "Adenekan",
    company: "KLA Corporation",
    stage: "Idea stage",
    industry: "Hardware / Manufacturing",
    primaryFocus: "Go-to-market & customer acquisition",
    secondaryFoci: ["Refining pitch or company narrative"],
    mentor: { name: "Ed Sawma", company: "Ed Sawma Consulting", title: "Principal Consultant", initials: "ES", tags: ["Go-to-market", "Hardware / Manufacturing", "Idea stage"] },
  },
  {
    slug: "maab-iqbal",
    cohort: 4,
    first: "Maab", last: "Iqbal",
    company: "TBD",
    stage: "Idea stage",
    industry: "Media / Marketing / Advertising",
    primaryFocus: "Understanding the NJ/regional startup ecosystem",
    secondaryFoci: ["Clarifying near-term company priorities", "Product strategy & roadmap decisions"],
    mentor: { name: "Jeffrey Allen", company: "The Mariner Group, LLC", title: "CEO", initials: "JA", tags: ["NJ ecosystem guidance", "Media / Marketing", "Idea stage"] },
  },
  {
    slug: "rajesh-ivaturi",
    cohort: 4,
    first: "Rajesh", last: "Ivaturi",
    company: "SekurAI",
    stage: "MVP / Early build",
    industry: "Enterprise SaaS / B2B",
    primaryFocus: "Go-to-market & customer acquisition",
    secondaryFoci: [],
    mentor: { name: "Pavan Kumar", company: "3pm Ventures LLC", title: "Partner", initials: "PK", tags: ["Go-to-market", "Enterprise SaaS / B2B", "MVP stage"] },
  },
  {
    slug: "logan-jones",
    cohort: 4,
    first: "Logan", last: "Jones",
    company: "ticker",
    stage: "Early traction",
    industry: "Finance / Fintech",
    primaryFocus: "Business Model / Revenue Generation",
    secondaryFoci: ["Fundraising strategy & investor readiness"],
    mentor: { name: "Clare DeNicola", company: "the10company", title: "Principal", initials: "CD", tags: ["Business model", "Finance / Fintech", "Early traction"] },
  },
  {
    slug: "sharon-joseph",
    cohort: 4,
    first: "Sharon", last: "Joseph",
    company: "CREWASIS.AI",
    stage: "Revenue-generating",
    industry: "Enterprise SaaS / B2B",
    primaryFocus: "Fundraising strategy & investor readiness",
    secondaryFoci: ["Operational scaling and systems"],
    mentor: { name: "Joe Maruschak", company: "N/A", title: "N/A", initials: "JM", tags: ["Fundraising strategy", "Enterprise SaaS / B2B", "Revenue-generating"] },
  },
  {
    slug: "mark-kallback",
    cohort: 4,
    first: "Mark", last: "Kallback",
    company: "Clear-Sight",
    stage: "Early traction",
    industry: "Other",
    county: "Hunterdon",
    primaryFocus: "Sense-checking decisions with an experienced operator",
    secondaryFoci: [],
    mentor: { name: "Felicia Palmer", company: "tapyoca Inc", title: "CEO", initials: "FP", tags: ["Strategic sounding board", "Early traction"] },
  },
  {
    slug: "lianna-lariccia",
    cohort: 4,
    first: "Lianna", last: "LaRiccia",
    company: "Quanticore",
    stage: "MVP / Early build",
    industry: "Enterprise SaaS / B2B",
    county: "Passaic",
    primaryFocus: "Fundraising strategy & investor readiness",
    secondaryFoci: ["Refining pitch or company narrative"],
    mentor: { name: "Yuri Fiaschi", company: "Infobip", title: "VP of Strategic Partnerships and GTM", initials: "YF", tags: ["Fundraising strategy", "Enterprise SaaS / B2B", "MVP stage"] },
  },
  {
    slug: "han-nguyen",
    cohort: 4,
    first: "Han", last: "Nguyen",
    company: "Ox Group",
    stage: "Early traction",
    industry: "Finance / Fintech",
    county: "Mercer",
    primaryFocus: "Fundraising strategy & investor readiness",
    secondaryFoci: [],
    mentor: { name: "Soojin Choung", company: "Witness Creative Partners Inc.", title: "CEO", initials: "SC", tags: ["Fundraising strategy", "Finance / Fintech", "Early traction"] },
  },
  {
    slug: "mohammad-saleh-nikoopayan-tak",
    cohort: 4,
    first: "Mohammad Saleh", last: "Nikoopayan Tak",
    company: "TasteTwin AI",
    stage: "MVP / Early build",
    industry: "Retail / Marketplace / E-commerce",
    county: "Union",
    primaryFocus: "Product strategy & roadmap decisions",
    secondaryFoci: ["Go-to-market & customer acquisition", "Sense-checking decisions with an experienced operator"],
    mentor: { name: "Malak Atut", company: "Yalla Now AI", title: "Co-Founder", initials: "MA", tags: ["Product & roadmap", "Retail / E-commerce", "MVP stage"] },
  },
  {
    slug: "abhaya-pawar",
    cohort: 4,
    first: "Abhaya", last: "Pawar",
    company: "Ilika LLC",
    stage: "Early traction",
    industry: "Climate / Energy",
    county: "Middlesex",
    primaryFocus: "Go-to-market & customer acquisition",
    secondaryFoci: ["Fundraising strategy & investor readiness"],
    mentor: { name: "Dan Gura", company: "Hugo Neu", title: "Director BD/Consultant", initials: "DG", tags: ["Go-to-market", "Climate / Energy", "Early traction"] },
  },
  {
    slug: "parminder-singh",
    cohort: 4,
    first: "Parminder", last: "Singh",
    company: "DeepInspect.ai",
    stage: "Early traction",
    industry: "AI / Data / ML",
    county: "Middlesex",
    primaryFocus: "Go-to-market & customer acquisition",
    secondaryFoci: ["Fundraising strategy & investor readiness"],
    mentor: { name: "Orin Davis", company: "Quality of Life Laboratory", title: "Principal", initials: "OD", tags: ["Go-to-market", "AI / Data / ML", "Early traction"] },
  },
  {
    slug: "mehul-sompura",
    cohort: 4,
    first: "Mehul", last: "Sompura",
    company: "Diamond Hedge",
    stage: "Revenue-generating",
    industry: "Retail / Marketplace / E-commerce",
    county: "Monmouth",
    primaryFocus: "Fundraising strategy & investor readiness",
    secondaryFoci: ["Go-to-market & customer acquisition", "Preparing for a major inflection point (raise, launch, pivot, expansion)"],
    mentor: { name: "Mark Nelson", company: "Pivot Fuel", title: "CEO", initials: "MN", tags: ["Fundraising strategy", "Retail / E-commerce", "Revenue-generating"] },
  },
  {
    slug: "harshil-thakkar",
    cohort: 4,
    first: "Harshil", last: "Thakkar",
    company: "Newyorklife",
    stage: "Revenue-generating",
    industry: "Finance / Fintech",
    county: "Hudson",
    primaryFocus: "Understanding the NJ/regional startup ecosystem",
    secondaryFoci: ["Fundraising strategy & investor readiness", "Go-to-market & customer acquisition"],
    mentor: { name: "Bruno Bilik", company: "91.life", title: "Chief Revenue Officer", initials: "BB", tags: ["NJ ecosystem guidance", "Finance / Fintech", "Revenue-generating"] },
  },

  // ── COHORT 5 — Morrison ──────────────────────────────────────────────────
  {
    slug: "elisa-charters",
    cohort: 5,
    first: "Elisa", last: "Charters",
    company: "Juegos AI Lab",
    stage: "Early traction",
    industry: "Other",
    county: "Essex",
    primaryFocus: "Fundraising strategy & investor readiness",
    secondaryFoci: ["Preparing for a major inflection point", "Clarifying near-term company priorities"],
    mentor: { name: "ebun okubanjo", company: "mssuzie.io", title: "CEO/Co-Founder", initials: "EO", tags: ["Fundraising strategy", "Early traction"] },
  },
  {
    slug: "kima-danjou",
    cohort: 5,
    first: "Kima", last: "D'Anjou",
    company: "The Keenly Group LLC",
    stage: "Revenue-generating",
    industry: "Enterprise SaaS / B2B",
    county: "Bergen",
    primaryFocus: "Sense-checking decisions with an experienced operator",
    secondaryFoci: ["Clarifying near-term company priorities"],
    mentor: { name: "Wadnes Castelly", company: "KAPAB Marketing Consultancy LLC", title: "Founder", initials: "WC", tags: ["Strategic sounding board", "Enterprise SaaS / B2B", "Revenue-generating"] },
  },
  {
    slug: "andrea-ferguson-peterson",
    cohort: 5,
    first: "Andrea", last: "Ferguson Peterson",
    company: "Everyday Unstoppable",
    stage: "Revenue-generating",
    industry: "Retail / Marketplace / E-commerce",
    county: "Essex",
    primaryFocus: "Clarifying near-term company priorities",
    secondaryFoci: [],
    mentor: { name: "Soojin Choung", company: "Witness Creative Partners Inc.", title: "CEO", initials: "SC", tags: ["Founder decision-making", "Retail / E-commerce", "Revenue-generating"] },
  },
  {
    slug: "saurabh-gandhe",
    cohort: 5,
    first: "Saurabh", last: "Gandhe",
    company: "Creative Sprouts Inc",
    stage: "Revenue-generating",
    industry: "Media / Marketing / Advertising",
    primaryFocus: "Clarifying near-term company priorities",
    secondaryFoci: ["Product strategy & roadmap decisions", "Preparing for a major inflection point"],
    mentor: { name: "Marc Saint-Ulysse", company: "Northgate Operations", title: "Founder", initials: "MS", tags: ["Founder decision-making", "Media / Marketing", "Revenue-generating"] },
  },
  {
    slug: "rachel-hayes",
    cohort: 5,
    first: "Rachel", last: "Hayes",
    company: "Ravel Genetics",
    stage: "MVP / Early build",
    industry: "Enterprise SaaS / B2B",
    county: "Bergen",
    primaryFocus: "Fundraising strategy & investor readiness",
    secondaryFoci: ["Refining pitch or company narrative"],
    mentor: { name: "Yuri Fiaschi", company: "Infobip", title: "VP of Strategic Partnerships and GTM", initials: "YF", tags: ["Fundraising strategy", "Enterprise SaaS / B2B"] },
  },
  {
    slug: "jasmin-jones",
    cohort: 5,
    first: "Jasmin", last: "Jones",
    company: "JP Morgan Chase",
    stage: "Idea stage",
    industry: "Media / Marketing / Advertising",
    primaryFocus: "Go-to-market & customer acquisition",
    secondaryFoci: ["Refining pitch or company narrative"],
    mentor: { name: "Goncalo Esteves", company: "Self Defense 4 All LLC", title: "Founder and CEO", initials: "GE", tags: ["Go-to-market", "Media / Marketing", "Idea stage"] },
  },
  {
    slug: "natalie-kitts",
    cohort: 5,
    first: "Natalie", last: "Kitts",
    company: "The Zigzag Flow, Therapy Services",
    stage: "Early traction",
    industry: "Other",
    county: "Morris",
    primaryFocus: "Fundraising strategy & investor readiness",
    secondaryFoci: [],
    mentor: { name: "Vishal Soni", company: "Virid Biosciences", title: "CEO", initials: "VS", tags: ["Fundraising strategy", "Early traction"] },
  },
  {
    slug: "britney-medich",
    cohort: 5,
    first: "Britney", last: "Medich",
    company: "Brooklyn Navy Yard",
    stage: "MVP / Early build",
    industry: "Other",
    county: "Hudson",
    primaryFocus: "Product strategy & roadmap decisions",
    secondaryFoci: [],
    mentor: { name: "Connie Pascal", company: "Rutgers - School of Communication & Information", title: "Lecturer III", initials: "CP", tags: ["Product & roadmap", "MVP stage"] },
  },
  {
    slug: "kevin-navarro",
    cohort: 5,
    first: "Kevin", last: "Navarro",
    company: "MechSense Labs",
    stage: "MVP / Early build",
    industry: "AI / Data / ML",
    county: "Bergen",
    primaryFocus: "Refining pitch or company narrative",
    secondaryFoci: ["Go-to-market & customer acquisition", "Fundraising strategy & investor readiness"],
    mentor: { name: "Dennis Yuscavitch", company: "Accrete Inc.", title: "VP, Marketing", initials: "DY", tags: ["Pitch & narrative", "AI / Data / ML", "MVP stage"] },
  },
  {
    slug: "chandni-patel",
    cohort: 5,
    first: "Chandni", last: "Patel",
    company: "BOA (startup name undecided)",
    stage: "Idea stage",
    industry: "Other",
    county: "Middlesex",
    primaryFocus: "Go-to-market & customer acquisition",
    secondaryFoci: ["Refining pitch or company narrative"],
    mentor: { name: "Jessie Lee", company: "SmartTravel.com", title: "GTM, Health Insurance", initials: "JL", tags: ["Go-to-market", "Idea stage"] },
  },
  {
    slug: "daniel-patton",
    cohort: 5,
    first: "Daniel", last: "Patton",
    company: "DreamEngine AI",
    stage: "MVP / Early build",
    industry: "AI / Data / ML",
    county: "Middlesex",
    primaryFocus: "Fundraising strategy & investor readiness",
    secondaryFoci: ["Refining pitch or company narrative"],
    mentor: { name: "Joe Maruschak", company: "N/A", title: "N/A", initials: "JM", tags: ["Fundraising strategy", "AI / Data / ML", "MVP stage"] },
  },
  {
    slug: "jeremy-ruiz-villavicencio",
    cohort: 5,
    first: "Jeremy", last: "Ruiz Villavicencio",
    company: "Menti",
    stage: "Idea stage",
    industry: "Media / Marketing / Advertising",
    county: "Union",
    primaryFocus: "Understanding the NJ/regional startup ecosystem",
    secondaryFoci: ["Clarifying near-term company priorities"],
    mentor: { name: "Dee Marshall", company: "AI Training Plus", title: "Chief Executive Officer", initials: "DM", tags: ["NJ ecosystem guidance", "Idea stage"] },
  },
  {
    slug: "jordan-river-samuel",
    cohort: 5,
    first: "Jordan-River", last: "Samuel",
    company: "tapyoca",
    stage: "Early traction",
    industry: "Enterprise SaaS / B2B",
    county: "Hudson",
    primaryFocus: "Go-to-market & customer acquisition",
    secondaryFoci: ["Understanding the NJ/regional startup ecosystem"],
    mentor: { name: "Jennifer Jolley", company: "PDHI", title: "CEO & Founder", initials: "JJ", tags: ["Go-to-market", "Enterprise SaaS / B2B", "Early traction"] },
  },
  {
    slug: "chirag-shah",
    cohort: 5,
    first: "Chirag", last: "Shah",
    company: "Crestwood Digital",
    stage: "Early traction",
    industry: "Other",
    primaryFocus: "Go-to-market & customer acquisition",
    secondaryFoci: ["Refining pitch or company narrative", "Operational scaling and systems"],
    mentor: { name: "Jennifer Jolley", company: "PDHI", title: "CEO & Founder", initials: "JJ", tags: ["Go-to-market", "Early traction"] },
  },
  {
    slug: "shippy-singh",
    cohort: 5,
    first: "Shippy", last: "Singh",
    company: "Staytus",
    stage: "MVP / Early build",
    industry: "AI / Data / ML",
    primaryFocus: "Preparing for a major inflection point (raise, launch, pivot, expansion)",
    secondaryFoci: ["Fundraising strategy & investor readiness"],
    mentor: { name: "Sid Nag", company: "Tekonyx", title: "President and CEO", initials: "SN", tags: ["Inflection-point navigation", "AI / Data / ML", "MVP stage"] },
  },

  // ── TEST ENTRY ───────────────────────────────────────────────────────────
  {
    slug: "kennedy",
    cohort: 1,
    first: "Kennedy", last: "Test",
    company: "Test Company",
    stage: "Early traction",
    industry: "Other",
    county: "Middlesex",
    primaryFocus: "Sense-checking decisions with an experienced operator",
    secondaryFoci: ["Go-to-market & customer acquisition"],
    mentorUnlocked: true,
    mentor: { name: "MJ", company: "Test Organization", title: "Lead Mentor", initials: "MJ", tags: ["Strategic sounding board", "Go-to-market"] },
  },
];

// Prompt library keyed by focus area
export const PROMPTS = {
  "go-to-market": {
    theme: "Your go-to-market strategy",
    questions: [
      "Who is your ideal first customer, and why? What specific problem are you solving for them that no one else solves as well?",
      "What does your current customer acquisition process look like? Where does it break down, and what would \"working well\" look like in three months?",
      "What assumptions about your market or buyer have you not yet tested? What would change if one turned out to be wrong?",
    ],
  },
  "fundraising": {
    theme: "Your fundraising strategy",
    questions: [
      "Where are you in your fundraising journey right now? What have you tried, and what's the honest story of why it hasn't moved as fast as you'd like?",
      "What does a compelling investor conversation look like for your company? What questions do investors keep asking that you struggle to answer?",
      "What does your company need to demonstrate before investors will feel confident writing a check? How realistic is that milestone in the next 90 days?",
    ],
  },
  "pitch-narrative": {
    theme: "Your pitch & company narrative",
    questions: [
      "How do you currently describe your company to a stranger in two sentences? What part of that feels fuzzy or hard to explain?",
      "What's the core insight behind your company that most people don't yet see? How do you communicate it without losing the room?",
      "Think about the last time you pitched — what landed best, and what fell flat? What does that tell you about your narrative?",
    ],
  },
  "product-roadmap": {
    theme: "Your product strategy & roadmap",
    questions: [
      "What is the single most important problem your product solves today? Is that still the right problem to be solving?",
      "How do you currently make decisions about what to build next? What information do you have, and what do you wish you had?",
      "Where does user feedback end and your own vision begin? How do you balance what users ask for with what they actually need?",
    ],
  },
  "inflection-point": {
    theme: "Navigating your next inflection point",
    questions: [
      "What is the specific inflection point you're preparing for — a raise, a launch, a pivot, or an expansion? What does success look like?",
      "What are the two or three things that absolutely must go right for this transition to work? What would cause each one to fail?",
      "Who else has navigated a similar inflection point? What can you learn from them before you go through it yourself?",
    ],
  },
  "sounding-board": {
    theme: "Sense-checking your decisions",
    questions: [
      "What is the biggest decision you're wrestling with right now? What are you leaning toward, and what's making you hesitate?",
      "When you think about advice you've received so far, what's been most useful — and what have you most disagreed with?",
      "What would you do right now if you weren't afraid of being wrong? What's holding you back?",
    ],
  },
  "founder-decisions": {
    theme: "Founder decision-making & priorities",
    questions: [
      "What are the top three things on your plate right now? If you could only do one in the next 30 days, which would move the needle most?",
      "Where are you spending time that you know isn't the highest-leverage use of your energy? What would need to be true for you to stop?",
      "What does \"good progress\" look like for you at the end of this program? What do you want to be able to say you figured out?",
    ],
  },
  "hiring-leadership": {
    theme: "Hiring, team & leadership",
    questions: [
      "What does your team look like today, and what's the most critical role you need to fill or develop in the next three months?",
      "Where are you currently the bottleneck in your own organization? What would it take to change that?",
      "What kind of leader are you trying to become? What are the gaps between how you currently lead and how you want to lead?",
    ],
  },
  "operational-scaling": {
    theme: "Operational scaling & systems",
    questions: [
      "What part of your business runs on you personally — where your absence would cause things to break? What would it take to change that?",
      "What are the two or three operational bottlenecks that limit how fast you can grow right now?",
      "What does a well-run version of your company look like in 12 months? What systems need to exist that don't today?",
    ],
  },
  "nj-ecosystem": {
    theme: "Navigating the NJ startup ecosystem",
    questions: [
      "What do you know about the New Jersey startup ecosystem today — the resources, networks, investors? Where are the gaps?",
      "Who in NJ do you most want to connect with — founders, investors, operators — and what would make those relationships genuinely valuable?",
      "What would it mean for your company to be truly plugged into the local ecosystem? What does that look like in practice?",
    ],
  },
};

export function getFocusKey(focus) {
  const f = (focus || "").toLowerCase();
  if (f.includes("go-to-market") || f.includes("customer acq") || f.includes("business model") || f.includes("revenue gen")) return "go-to-market";
  if (f.includes("fundrais")) return "fundraising";
  if (f.includes("pitch") || f.includes("narrative")) return "pitch-narrative";
  if (f.includes("product") || f.includes("roadmap")) return "product-roadmap";
  if (f.includes("inflection") || f.includes("launch") || f.includes("pivot")) return "inflection-point";
  if (f.includes("sense-check") || f.includes("sounding board") || f.includes("operator")) return "sounding-board";
  if (f.includes("clarif") || f.includes("priorit") || f.includes("decision")) return "founder-decisions";
  if (f.includes("hiring") || f.includes("team") || f.includes("leadership")) return "hiring-leadership";
  if (f.includes("operat") || f.includes("scaling") || f.includes("systems")) return "operational-scaling";
  if (f.includes("ecosystem") || f.includes("nj") || f.includes("regional")) return "nj-ecosystem";
  return "sounding-board";
}

export function getMenteeBySlug(slug) {
  const m = MENTEES.find((m) => m.slug === slug) || null;
  if (!m) return null;
  // linkedin: LinkedIn profile URL — fill in per mentee to enable directory links
  // photo: headshot URL (any public image) — fill in per mentee for directory
  // mentorUnlocked: set to true once admin confirms orientation attendance
  const defaultMilestones = {
    onboarding: false,
    mentorMatched: false,
    edu1: false, edu2: false, edu3: false,
    mentorSession1: false, mentorSession2: false, mentorSession3: false,
    midpoint: false,
    endSurvey: false,
    summit: false,
    certificate: false,
  };
  return {
    linkedin: null, photo: null, mentorUnlocked: false,
    milestones: { ...defaultMilestones, ...(m.milestones || {}) },
    ...m,
  };
}
