// GENERATED FILE — rebuild from uplift-2026-completers.csv + lib/mentees.js.
//
// The Summer 2026 graduates: everyone who completed the program, joined to
// their roster record for photo, industry, stage, and focus. This is the back
// half of the Founder Lookbook, four to a page.
//
// Public by design, so it carries only what the alumni already show publicly:
// name, company, what they were working on, their mentor, and LinkedIn. No
// email, no phone, no revenue, no demographics.
//
// Built 2026-09-01 from 47 graduates (44 with photos).

export const UPLIFT_ALUMNI = [
  {
    "slug": "abhaya-pawar",
    "first": "Abhaya",
    "last": "Pawar",
    "company": "Ilika LLC",
    "industry": "Climate / Energy",
    "stage": "Early traction",
    "county": "Middlesex",
    "primaryFocus": "Go-to-market & customer acquisition",
    "photo": "/photos/abhaya-pawar.jpg",
    "linkedin": "https://www.linkedin.com/me?trk=p_mwlite_feed-secondary_nav",
    "mentor": "Stella Alvo",
    "mentorCompany": "Westfield Consulting LLC"
  },
  {
    "slug": "adeola-adeoye-davids",
    "first": "Adeola",
    "last": "Adeoye-Davids",
    "company": "Local Window",
    "industry": "Media / Marketing / Advertising",
    "stage": "MVP / Early build",
    "county": "Passaic",
    "primaryFocus": "Operational scaling and systems",
    "photo": "/photos/adeola-adeoye-davids.jpg",
    "linkedin": "https://www.linkedin.com/in/adeola-adeoye-davids/",
    "mentor": "Aditi Sinha",
    "mentorCompany": "MarketCast"
  },
  {
    "slug": "alisha-sharma",
    "first": "Alisha",
    "last": "Sharma",
    "company": "Undecided",
    "industry": "Other",
    "stage": "Idea stage",
    "county": "Morris",
    "primaryFocus": "Product strategy & roadmap decisions",
    "photo": "/photos/alisha-sharma.jpg",
    "linkedin": null,
    "mentor": "Felicia Palmer",
    "mentorCompany": "tapyoca Inc"
  },
  {
    "slug": "aliya-laliwala",
    "first": "Aliya",
    "last": "Laliwala",
    "company": "Campus Marketplace",
    "industry": "Retail / Marketplace / E-commerce",
    "stage": "Early traction",
    "county": "Bergen",
    "primaryFocus": "Preparing for a major inflection point (raise, launch, pivot, expansion)",
    "photo": "/photos/aliya-laliwala.jpg",
    "linkedin": "https://www.linkedin.com/in/aliya-laliwala/",
    "mentor": "Christina Dorando",
    "mentorCompany": "Cresthill Academy"
  },
  {
    "slug": "angela-aricatt",
    "first": "Angela",
    "last": "Aricatt",
    "company": "Get Empathix",
    "industry": "Enterprise SaaS / B2B",
    "stage": "Idea stage",
    "county": "Essex",
    "primaryFocus": "Sense-checking decisions with an experienced operator",
    "photo": "/photos/angela-aricatt.jpg",
    "linkedin": "https://www.linkedin.com/in/angela-aricatt/",
    "mentor": "Jennifer D'Angelo",
    "mentorCompany": "NJII"
  },
  {
    "slug": "annalyce-dagostino-gavin",
    "first": "Annalyce",
    "last": "D'Agostino-Gavin",
    "company": "Focus Posters\u00ae",
    "industry": "Other",
    "stage": "Early traction",
    "county": null,
    "primaryFocus": "Preparing for a major inflection point (raise, launch, pivot, expansion)",
    "photo": "/photos/annalyce-dagostino-gavin.png",
    "linkedin": "https://www.linkedin.com/in/annalycedagostino",
    "mentor": "Stephen Makinen",
    "mentorCompany": "Lockheed Martin"
  },
  {
    "slug": "anthony-caruso",
    "first": "Anthony",
    "last": "Caruso",
    "company": "Contextral",
    "industry": "AI / Data / ML",
    "stage": "Early traction",
    "county": "Ocean",
    "primaryFocus": "Go-to-market & customer acquisition",
    "photo": "/photos/anthony-caruso.jpg",
    "linkedin": "https://www.linkedin.com/in/giftyanane/",
    "mentor": "Ed Sawma",
    "mentorCompany": "Ed Sawma Consulting"
  },
  {
    "slug": "bejan-moers",
    "first": "Bejan",
    "last": "Moers",
    "company": "United Solution",
    "industry": "Other",
    "stage": "Early traction",
    "county": "Hudson",
    "primaryFocus": "Preparing for a major inflection point (raise, launch, pivot, expansion)",
    "photo": "/photos/bejan-moers.jpg",
    "linkedin": "https://www.linkedin.com/in/bejanmoers/",
    "mentor": "Jose Gabriel Carrasco Ramirez",
    "mentorCompany": "Quarks Advantage Corp"
  },
  {
    "slug": "chandni-patel",
    "first": "Chandni",
    "last": "Patel",
    "company": "BOA (startup name undecided)",
    "industry": "Other",
    "stage": "Idea stage",
    "county": "Middlesex",
    "primaryFocus": "Go-to-market & customer acquisition",
    "photo": "/photos/chandni-patel.jpg",
    "linkedin": null,
    "mentor": "Jessie Lee",
    "mentorCompany": "SmartTravel.com"
  },
  {
    "slug": "chirag-shah",
    "first": "Chirag",
    "last": "Shah",
    "company": "Crestwood Digital",
    "industry": "Other",
    "stage": "Early traction",
    "county": null,
    "primaryFocus": "Go-to-market & customer acquisition",
    "photo": "/photos/chirag-shah.jpg",
    "linkedin": "https://www.linkedin.com/in/chiragdshah/",
    "mentor": "Jennifer Jolley",
    "mentorCompany": "PDHI"
  },
  {
    "slug": "daniel-patton",
    "first": "Daniel",
    "last": "Patton",
    "company": "DreamEngine AI",
    "industry": "AI / Data / ML",
    "stage": "MVP / Early build",
    "county": "Middlesex",
    "primaryFocus": "Fundraising strategy & investor readiness",
    "photo": "/photos/daniel-patton.jpg",
    "linkedin": "https://www.linkedin.com/in/daniel-patton/",
    "mentor": "Joe Maruschak",
    "mentorCompany": "Independent"
  },
  {
    "slug": "debbiedouglas",
    "first": "Debbie",
    "last": "Douglas",
    "company": "3DHR Consulting, LLC",
    "industry": null,
    "stage": null,
    "county": null,
    "primaryFocus": null,
    "photo": "/photos/debbiedouglas.jpg",
    "linkedin": "https://www.linkedin.com/in/537718",
    "mentor": "Wadnes Castelly",
    "mentorCompany": "KAPAB Marketing Consultancy LLC"
  },
  {
    "slug": "ekaterina-kashkina",
    "first": "Ekaterina",
    "last": "Kashkina",
    "company": "Stealth-mode molecular diagnostics startup",
    "industry": "Other",
    "stage": "MVP / Early build",
    "county": "Camden",
    "primaryFocus": "Fundraising strategy & investor readiness",
    "photo": "/photos/ekaterina-kashkina.jpg",
    "linkedin": null,
    "mentor": "Marty Coleman",
    "mentorCompany": "Entrepreneur/Investor/Mentor"
  },
  {
    "slug": "elaf-mahmoud",
    "first": "Elaf",
    "last": "Mahmoud",
    "company": "Elune Health",
    "industry": "CPG / Consumer Brands",
    "stage": "Idea stage",
    "county": "Morris",
    "primaryFocus": "Refining pitch or company narrative",
    "photo": "/photos/elaf-mahmoud.jpg",
    "linkedin": null,
    "mentor": "Vishal Goyal",
    "mentorCompany": "Orchestra Prime"
  },
  {
    "slug": "eliana-zebro",
    "first": "Eliana",
    "last": "Zebro",
    "company": "Freelance Audio (Pre-LLC)",
    "industry": "Media / Marketing / Advertising",
    "stage": "Idea stage",
    "county": "Warren",
    "primaryFocus": "Clarifying near-term company priorities",
    "photo": "/photos/eliana-zebro.jpg",
    "linkedin": "https://www.linkedin.com/in/eliana-zebro-41bb4a152/",
    "mentor": "Aditi Sinha",
    "mentorCompany": "MarketCast"
  },
  {
    "slug": "elisa-charters",
    "first": "Elisa",
    "last": "Charters",
    "company": "Juegos AI Lab",
    "industry": "Other",
    "stage": "Early traction",
    "county": "Essex",
    "primaryFocus": "Fundraising strategy & investor readiness",
    "photo": "/photos/elisa-charters.jpg",
    "linkedin": "https://www.linkedin.com/in/elisacharterslatina",
    "mentor": "Jossy Harrington",
    "mentorCompany": "mssuzie.io"
  },
  {
    "slug": "evan-peneiras",
    "first": "Evan",
    "last": "Peneiras",
    "company": "Nooriva",
    "industry": "AI / Data / ML",
    "stage": "MVP / Early build",
    "county": "Essex",
    "primaryFocus": "Understanding the NJ/regional startup ecosystem",
    "photo": "/photos/evan-peneiras.png",
    "linkedin": null,
    "mentor": "Anand Rai",
    "mentorCompany": "Verizon / Stevens Institute of Technology"
  },
  {
    "slug": "gifty-anane",
    "first": "Gifty",
    "last": "Anane",
    "company": "Wash Lodge",
    "industry": "Retail / Marketplace / E-commerce",
    "stage": "MVP / Early build",
    "county": "Middlesex",
    "primaryFocus": "Sense-checking decisions with an experienced operator",
    "photo": "/photos/gifty-anane.jpg",
    "linkedin": null,
    "mentor": "Andrew Jacobs",
    "mentorCompany": "Jacobs Ventures"
  },
  {
    "slug": "gunjan-aggarwal",
    "first": "Gunjan",
    "last": "Aggarwal",
    "company": "Virre",
    "industry": "AI / Data / ML",
    "stage": "Early traction",
    "county": "Middlesex",
    "primaryFocus": "Fundraising strategy & investor readiness",
    "photo": "/photos/gunjan-aggarwal.jpg",
    "linkedin": "https://www.linkedin.com/in/gunjanaggarwal/",
    "mentor": "Anatole Norland",
    "mentorCompany": "Rewriting The Code"
  },
  {
    "slug": "hamza-zafar",
    "first": "Hamza",
    "last": "Zafar",
    "company": "HHALI LLC",
    "industry": "AI / Data / ML",
    "stage": "MVP / Early build",
    "county": "Middlesex",
    "primaryFocus": "Go-to-market & customer acquisition",
    "photo": "/photos/hamza-zafar.jpg",
    "linkedin": "https://www.linkedin.com/in/hamza-ali-zafar/",
    "mentor": "Rahul Mehendale",
    "mentorCompany": "Live150.ai"
  },
  {
    "slug": "harshil-thakkar",
    "first": "Harshil",
    "last": "Thakkar",
    "company": "Newyorklife",
    "industry": "Finance / Fintech",
    "stage": "Revenue-generating",
    "county": "Hudson",
    "primaryFocus": "Understanding the NJ/regional startup ecosystem",
    "photo": "/photos/harshil-thakkar.jpg",
    "linkedin": "https://www.linkedin.com/in/harshil-thakkar-b44b46170?utm_source=share_via&utm_content=profile&utm_medium=member_android",
    "mentor": "Bruno Bilik",
    "mentorCompany": "91.life"
  },
  {
    "slug": "jamescurley",
    "first": "James",
    "last": "Curley",
    "company": "Quanticore",
    "industry": null,
    "stage": null,
    "county": null,
    "primaryFocus": null,
    "photo": "/photos/jamescurley.jpg",
    "linkedin": null,
    "mentor": "Yuri Fiaschi",
    "mentorCompany": "Infobip"
  },
  {
    "slug": "jean-guerdy-paul",
    "first": "Jean Guerdy",
    "last": "Paul",
    "company": "TETHRRA",
    "industry": "Enterprise SaaS / B2B",
    "stage": "Early traction",
    "county": "Monmouth",
    "primaryFocus": "Refining pitch or company narrative",
    "photo": "/photos/jean-guerdy-paul.jpg",
    "linkedin": null,
    "mentor": "Roman Tsibulevskiy",
    "mentorCompany": "Dentons US LLP"
  },
  {
    "slug": "jeremy-ruiz-villavicencio",
    "first": "Jeremy",
    "last": "Ruiz Villavicencio",
    "company": "Menti",
    "industry": "Media / Marketing / Advertising",
    "stage": "Idea stage",
    "county": "Union",
    "primaryFocus": "Understanding the NJ/regional startup ecosystem",
    "photo": "/photos/jeremy-ruiz-villavicencio.png",
    "linkedin": null,
    "mentor": "Dee Marshall",
    "mentorCompany": "AI Training Plus"
  },
  {
    "slug": "jhamar-youngblood",
    "first": "Jhamar",
    "last": "Youngblood",
    "company": "Brickcity",
    "industry": "Other",
    "stage": "Early traction",
    "county": "Essex",
    "primaryFocus": "Go-to-market & customer acquisition",
    "photo": "/photos/jhamar-youngblood.jpg",
    "linkedin": "https://www.linkedin.com/in/jhamartian?utm_source=share_via&utm_content=profile&utm_medium=member_ios",
    "mentor": "Marty Coleman",
    "mentorCompany": "Entrepreneur/Investor/Mentor"
  },
  {
    "slug": "jordan-river-samuel",
    "first": "Jordan-River",
    "last": "Samuel",
    "company": "tapyoca",
    "industry": "Enterprise SaaS / B2B",
    "stage": "Early traction",
    "county": "Hudson",
    "primaryFocus": "Go-to-market & customer acquisition",
    "photo": "/photos/jordan-river-samuel.jpg",
    "linkedin": "https://www.linkedin.com/in/jordan-river-samuel-2a25541a6/",
    "mentor": "Jennifer Jolley",
    "mentorCompany": "PDHI"
  },
  {
    "slug": "kevin-navarro",
    "first": "Kevin",
    "last": "Navarro",
    "company": "MechSense Labs",
    "industry": "AI / Data / ML",
    "stage": "MVP / Early build",
    "county": "Bergen",
    "primaryFocus": "Refining pitch or company narrative",
    "photo": "/photos/kevin-navarro.png",
    "linkedin": null,
    "mentor": "Dennis Yuscavitch",
    "mentorCompany": "Accrete Inc."
  },
  {
    "slug": "kima-danjou",
    "first": "Kima",
    "last": "D'Anjou",
    "company": "The Keenly Group LLC",
    "industry": "Enterprise SaaS / B2B",
    "stage": "Revenue-generating",
    "county": "Bergen",
    "primaryFocus": "Sense-checking decisions with an experienced operator",
    "photo": "/photos/kima-danjou.jpg",
    "linkedin": "https://www.linkedin.com/in/kima-danjou-mba",
    "mentor": "Wadnes Castelly",
    "mentorCompany": "KAPAB Marketing Consultancy LLC"
  },
  {
    "slug": "lianna-lariccia",
    "first": "Lianna",
    "last": "LaRiccia",
    "company": "Quanticore",
    "industry": "Enterprise SaaS / B2B",
    "stage": "MVP / Early build",
    "county": "Passaic",
    "primaryFocus": "Fundraising strategy & investor readiness",
    "photo": "/photos/lianna-lariccia.png",
    "linkedin": null,
    "mentor": "Yuri Fiaschi",
    "mentorCompany": "Infobip"
  },
  {
    "slug": "lina-escobar",
    "first": "Lina",
    "last": "Escobar",
    "company": "Sweet Aurora Soap & Candle",
    "industry": "CPG / Consumer Brands",
    "stage": "Revenue-generating",
    "county": null,
    "primaryFocus": "Go-to-market & customer acquisition",
    "photo": "/photos/lina-escobar.jpg",
    "linkedin": "https://www.linkedin.com/in/lina-escobar-13809a8b?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=ios_app",
    "mentor": "Clare DeNicola",
    "mentorCompany": "the10company"
  },
  {
    "slug": "logan-jones",
    "first": "Logan",
    "last": "Jones",
    "company": "ticker",
    "industry": "Finance / Fintech",
    "stage": "Early traction",
    "county": null,
    "primaryFocus": "Business Model / Revenue Generation",
    "photo": "/photos/logan-jones.jpg",
    "linkedin": "https://www.linkedin.com/in/loganjones23/",
    "mentor": "Clare DeNicola",
    "mentorCompany": "the10company"
  },
  {
    "slug": "natalie-kitts",
    "first": "Natalie",
    "last": "Kitts",
    "company": "The Zigzag Flow, Therapy Services",
    "industry": "Other",
    "stage": "Early traction",
    "county": "Morris",
    "primaryFocus": "Fundraising strategy & investor readiness",
    "photo": "/photos/natalie-kitts.jpg",
    "linkedin": "https://www.linkedin.com/in/natalie-kitts-4b725424/",
    "mentor": "Vishal Soni",
    "mentorCompany": "Virid Biosciences"
  },
  {
    "slug": "nina-mladenovski",
    "first": "Nina",
    "last": "Mladenovski",
    "company": "Zenia Graph",
    "industry": "AI / Data / ML",
    "stage": "Revenue-generating",
    "county": null,
    "primaryFocus": "Go-to-market & customer acquisition",
    "photo": "/photos/nina-mladenovski.png",
    "linkedin": "https://linkedin.com/in/ahmedmetwoali",
    "mentor": "Miquel de Quadras",
    "mentorCompany": "Atomian"
  },
  {
    "slug": "paula-machado-jackler",
    "first": "Paula",
    "last": "Machado Jackler",
    "company": "Ozzie",
    "industry": "Finance / Fintech",
    "stage": "MVP / Early build",
    "county": null,
    "primaryFocus": "Go-to-market & customer acquisition",
    "photo": "/photos/paula-machado-jackler.jpg",
    "linkedin": "https://www.linkedin.com/in/kipsbaydan",
    "mentor": "Eric Schmalzbauer",
    "mentorCompany": "Prospective"
  },
  {
    "slug": "pearl-gabel",
    "first": "Pearl",
    "last": "Gabel",
    "company": null,
    "industry": "Media / Marketing / Advertising",
    "stage": "Idea stage",
    "county": null,
    "primaryFocus": "Clarifying near-term company priorities",
    "photo": "/photos/pearl-gabel.jpg",
    "linkedin": null,
    "mentor": "Jeffrey Allen",
    "mentorCompany": "The Mariner Group, LLC"
  },
  {
    "slug": "pierre-girgis",
    "first": "Pierre",
    "last": "Girgis",
    "company": "Veriflo LLC",
    "industry": "AI / Data / ML",
    "stage": "Idea stage",
    "county": "Bergen",
    "primaryFocus": "Product strategy & roadmap decisions",
    "photo": "/photos/pierre-girgis.jpg",
    "linkedin": null,
    "mentor": "Aizaz Shariff",
    "mentorCompany": "Stratsphere"
  },
  {
    "slug": "priyal-levine",
    "first": "Priyal",
    "last": "Levine",
    "company": "Wisdom & Wonder Wellness",
    "industry": "Other",
    "stage": "Idea stage",
    "county": "Morris",
    "primaryFocus": "Refining pitch or company narrative",
    "photo": "/photos/priyal-levine.jpg",
    "linkedin": "https://www.linkedin.com/in/priyal-levine-26b17740",
    "mentor": "Michael Baer",
    "mentorCompany": "TechCXO"
  },
  {
    "slug": "rachel-hayes",
    "first": "Rachel",
    "last": "Hayes",
    "company": "Ravel Genetics",
    "industry": "Enterprise SaaS / B2B",
    "stage": "MVP / Early build",
    "county": "Bergen",
    "primaryFocus": "Fundraising strategy & investor readiness",
    "photo": "/photos/rachel-hayes.jpg",
    "linkedin": null,
    "mentor": "Yuri Fiaschi",
    "mentorCompany": "Infobip"
  },
  {
    "slug": "radha-ratnala",
    "first": "Radha",
    "last": "Ratnala",
    "company": "Rekogni AI",
    "industry": "Enterprise SaaS / B2B",
    "stage": "MVP / Early build",
    "county": "Middlesex",
    "primaryFocus": "Go-to-market & customer acquisition",
    "photo": "/photos/radha-ratnala.jpg",
    "linkedin": null,
    "mentor": "Kenneth Jones",
    "mentorCompany": "Xerdict Group LLC"
  },
  {
    "slug": "rajesh-ivaturi",
    "first": "Rajesh",
    "last": "Ivaturi",
    "company": "SekurAI",
    "industry": "Enterprise SaaS / B2B",
    "stage": "MVP / Early build",
    "county": null,
    "primaryFocus": "Go-to-market & customer acquisition",
    "photo": "/photos/rajesh-ivaturi.jpg",
    "linkedin": null,
    "mentor": "Kenneth Jones",
    "mentorCompany": "Xerdict Group LLC"
  },
  {
    "slug": "sarah-inoue",
    "first": "Sarah",
    "last": "Inoue",
    "company": "Crafty Dessert LLC",
    "industry": "Retail / Marketplace / E-commerce",
    "stage": "Early traction",
    "county": "Bergen",
    "primaryFocus": "Preparing for a major inflection point (raise, launch, pivot, expansion)",
    "photo": "/photos/sarah-inoue.png",
    "linkedin": null,
    "mentor": "Christina Dorando",
    "mentorCompany": "Cresthill Academy"
  },
  {
    "slug": "shanthi-viswanathan",
    "first": "Shanthi",
    "last": "Viswanathan",
    "company": "Infivista Inc",
    "industry": "Other",
    "stage": "Early traction",
    "county": "Hudson",
    "primaryFocus": "Go-to-market & customer acquisition",
    "photo": "/photos/shanthi-viswanathan.jpg",
    "linkedin": "https://www.linkedin.com/in/shanthi-viswanathan-9890861/",
    "mentor": "Marc Saint-Ulysse",
    "mentorCompany": "Northgate Operations"
  },
  {
    "slug": "sharon-joseph",
    "first": "Sharon",
    "last": "Joseph",
    "company": "CREWASIS.AI",
    "industry": "Enterprise SaaS / B2B",
    "stage": "Revenue-generating",
    "county": null,
    "primaryFocus": "Fundraising strategy & investor readiness",
    "photo": "/photos/sharon-joseph.jpg",
    "linkedin": "https://www.linkedin.com/in/sharonemilyjoseph/",
    "mentor": "Joe Spivack",
    "mentorCompany": "Jumpstart NJ Angel Network"
  },
  {
    "slug": "shell-bobev",
    "first": "Shell",
    "last": "Bobev",
    "company": "Disrupt The Gap",
    "industry": "Government / Civic / Policy",
    "stage": "Revenue-generating",
    "county": "Morris",
    "primaryFocus": "Product strategy & roadmap decisions",
    "photo": "/photos/shell-bobev.jpg",
    "linkedin": "https://www.linkedin.com/in/shellbobev/",
    "mentor": "Jennifer D'Angelo",
    "mentorCompany": "NJII"
  },
  {
    "slug": "sonali-chilupuri",
    "first": "Sonali",
    "last": "Chilupuri",
    "company": "Recky Solutions LLC",
    "industry": "Enterprise SaaS / B2B",
    "stage": "Early traction",
    "county": "Middlesex",
    "primaryFocus": "Go-to-market & customer acquisition",
    "photo": "/photos/sonali-chilupuri.png",
    "linkedin": "https://www.linkedin.com/in/sonalichilupuri/",
    "mentor": "Eric Schmalzbauer",
    "mentorCompany": "Prospective"
  },
  {
    "slug": "stephanie-scott-bradshaw",
    "first": "Stephanie",
    "last": "Scott-Bradshaw",
    "company": "First and Last PR",
    "industry": "Media / Marketing / Advertising",
    "stage": "Revenue-generating",
    "county": "Hudson",
    "primaryFocus": "Sense-checking decisions with an experienced operator",
    "photo": "/photos/stephanie-scott-bradshaw.jpg",
    "linkedin": "https://www.linkedin.com/in/stephanie-scott-bradshaw",
    "mentor": "Orin Davis",
    "mentorCompany": "Quality of Life Laboratory"
  },
  {
    "slug": "tosca-marleen",
    "first": "Tosca",
    "last": "Marleen",
    "company": "Tend to Belle",
    "industry": "Retail / Marketplace / E-commerce",
    "stage": "MVP / Early build",
    "county": null,
    "primaryFocus": "Hiring, team structure & leadership",
    "photo": "/photos/tosca-marleen.jpg",
    "linkedin": null,
    "mentor": "Natalie Kaminski",
    "mentorCompany": "JetRockets"
  }
];
